create database  QL_NhanSu_new 
go

CREATE TABLE [dbo].[DUAN](
	[MADA] [char](10) NOT NULL,
	[TENDA] [nvarchar](50) NULL,
	[DIADIEM] [nvarchar](50) NULL,
	[MAPB] [char](10) NULL,
	[TONGSOGIO] [float] NULL,
 CONSTRAINT [PK_DUAN] PRIMARY KEY CLUSTERED 
(
	[MADA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO


CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [char](10) NOT NULL,
	[TENNV] [nvarchar](50) NULL,
	[NGAYSINH] [date] NULL,
	[GT] [nvarchar](50) NULL,
	[MANGS] [char](10) NULL,
	[MAPB] [char](10) NULL,
	[BACLUONG] [int] NULL,
	[QUEQUAN] [nvarchar](50) NULL,
	[ACCOUNT] [varchar](50) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO


CREATE TABLE [dbo].[PHONGBAN](
	[MAPB] [char](10) NOT NULL,
	[TENPB] [nvarchar](50) NULL,
	[MATP] [char](10) NULL,
	[DIADIEM] [nvarchar](50) NULL,
	[NGAYNC] [date] NULL,
 CONSTRAINT [PK_PHONGBAN] PRIMARY KEY CLUSTERED 
(
	[MAPB] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO



CREATE TABLE [dbo].[PHANCONG](
	[MANV] [char](10) NOT NULL,
	[MADA] [char](10) NOT NULL,
	[SOGIO] [float] NULL,
 CONSTRAINT [PK_PHANCONG] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[MADA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[THANNHAN](
	[HOTEN] [nvarchar](50) NOT NULL,
	[NGAYSINH] [date] NULL,
	[GT] [nvarchar](50) NULL,
	[MANV] [char](10) NOT NULL,
	[QUANHE] [nvarchar](50) NULL,
 CONSTRAINT [PK_THANNHAN] PRIMARY KEY CLUSTERED 
(
	[HOTEN] ASC,
	[MANV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO


CREATE TABLE [dbo].[LUONG](
	[BACLUONG] [int] NOT NULL,
	[LUONGCOBAN] [int] NULL,
	[HESOLUONG] [float] NULL,
	[HESOPHUCAP] [float] NULL,
 CONSTRAINT [PK_LUONG] PRIMARY KEY CLUSTERED 
(
	[BACLUONG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



CREATE TABLE [dbo].[TAIKHOAN](
	[ACCOUNT] [varchar](50) NOT NULL,
	[PASSWORD] [varchar](50) NULL,
	[ACCESS] [nchar](3) NULL,
 CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY CLUSTERED 
(
	[ACCOUNT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO